### ISSUE TITLE
Compiler requirement tied to test candidate version

### ISSUE THREAD

**Issue by lstandage** [chipKIT32/chipKIT-importer#10]
The importer currently requires the following version of XC32:

1.43-TC5

But installing 1.43-RC1 gives an error.

It looks like Requirements.java has the version too long and needs to be shortened.

**Comment by gholdys** [comment]
Fixed with version 0.9.11. Please verify.

**Comment by EmbeddedMan** [comment]
Do we have a link for the new RC compiler?

Brian

**Comment by guymc** [comment]
Uploading now, will appear here in about 5 minutes:

https://microchip.box.com/s/3rtrjbct27femocf6xyvfdsjxp633xrs

Guy

**Comment by EmbeddedMan** [comment]
Interesting - I'm still using plugin version 0.9.9, and with the new
compiler, (1.43 RC1) I had no trouble importing or building a sketch.

Hmmm.

*Brian

**Comment by lstandage** [comment]
Did you remove the previous compiler version?

**Comment by EmbeddedMan** [comment]
Ahh, no. I did not. I just installed the new one, so my machine had both.

*Brian

**Comment by lstandage** [comment]
The plugin now does work with the new compiler.

But a question.

From the code, it looks like the importer is checking the path of the compiler to see whether it is the correct version. Will this handle future versions of the compiler, say, 1.44?

How will it handle situations where the user has installed the compiler in a different directory than the default?

Not that we can cover all situations, but I wonder if we can get the version directly from the compiler itself.

Finally, how do we tell which compiler is valid? I think the problem I had earlier today was because MPLAB X had a v1.43-TC5 in its tools list, but it wasn't actually on the computer. Can we test the compiler before selecting it, or can MPLAB X tell us that there may be a problem with that tool?

**Comment by lstandage** [comment]
Marking fixed unless proven otherwise.
