### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by shibshib** [chipKIT32/chipKIT-importer#21]
It's not clear whether this should be installed as a third party plugin or from the plugin manager. If installing thru the plugin manager, JNA dependency errors prevent the installation. 

![capture](https://cloud.githubusercontent.com/assets/5873393/25709066/3f2be922-30b6-11e7-8d8a-7a85be0e76a7.PNG)

**Comment by shibshib** [comment]
Nevermind, just used the .nbm file to import manually. Thanks.

**Comment by guymc** [comment]
Please note exactly which version of MPLAB X you are using.

We installed a work-around for the dependency issue (or so we thought.) A permanent fix is waiting for the next update of X.

Thanks!

________________________________

**Comment by shibshib** [comment]
For anyone else experiencing this issue: I was using MPLAB X v. 3.60. The workaround i did was download this repository and manually install the plugin from the plugin manager using the .nbm file included in this repository.
