### ISSUE TITLE
[Feature Request] Auto Scroll toggle on Serial Monitor

### ISSUE THREAD

**Issue by squintz** [chipKIT32/chipKIT-importer#6]
A feature of the Arduino Serial monitor that I use often is the Auto Scroll check box. The serial monitor bundled with the Importer does not seem to have an option for preventing Auto Scroll.

**Comment by gholdys** [comment]
There is no scroll lock check box but scrolling is controlled by user behaviour. If you scroll up to see some previous lines in the Serial Monitor, the automatic scrolling will be suspended. It resumes when you scroll down to the last line.

**Comment by squintz** [comment]
Thanks! That works.
